# Generated by Django 4.2 on 2023-07-19 07:01

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=0, help_text='+7 ( ) ___ - __ - __', max_length=128, region='RU'),
            preserve_default=False,
        ),
    ]
