# Generated by Django 4.2 on 2023-07-27 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='score',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Оценка меньше допустимой'), django.core.validators.MaxValueValidator(5, message='Оценка больше допустимой')], verbose_name='Оценка'),
            preserve_default=False,
        ),
    ]
