# Generated by Django 4.2 on 2023-07-27 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_reviews_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='slug',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='score',
            field=models.PositiveIntegerField(help_text='от 1 до 5', validators=[django.core.validators.MinValueValidator(1, message='Оценка меньше допустимой'), django.core.validators.MaxValueValidator(5, message='Оценка больше допустимой')], verbose_name='Оценка'),
        ),
    ]
