# Generated by Django 4.2 on 2023-08-14 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_review_product_stripe_id_alter_product_create_at_and_more'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='product',
            index_together=set(),
        ),
    ]
