# Generated by Django 4.2 on 2023-08-02 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_stripe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='review',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
