# Generated by Django 4.2 on 2023-07-10 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_stock',
            new_name='available',
        ),
    ]
